{
 "title": "My dash",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Filesystem available size",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\nnode_filesystem_avail_bytes{device=\"/dev/mapper/vgvagrant-root\", fstype=\"ext4\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"}",
     "legendFormat": "/"
    },
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sda1\", fstype=\"vfat\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/boot/efi\"}",
     "legendFormat": "/boot/efi"
    },
    {
     "expr": "node_filesystem_avail_bytes{device=\"tmpfs\", fstype=\"tmpfs\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/run\"}",
     "legendFormat": "/run"
    },
    {
     "expr": "node_filesystem_avail_bytes{device=\"tmpfs\", fstype=\"tmpfs\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/run/user/1000\"}",
     "legendFormat": "/run/user/1000"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "LA1"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "LA5"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "LA15"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "RAM FREE"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU LOAD"
    }
   ]
  }
 ]
}