apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ['sh', '-c', 'while true; do echo Salut! >> /mnt/local-storage/success.txt; sleep 5; done']
    volumeMounts:
    - mountPath: /mnt
      name: vol

  - name: network-multitool
    image: wbitt/network-multitool
    volumeMounts:
    - mountPath: /mnt
      name: vol

  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: local-volume

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /mnt/local-storage


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume
spec:
  storageClassName: "local-storage"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
