apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-volume
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.109
  share: /srv/nfs
reclaimPolicy: Delete
mountOptions:
- hard
- nfsvers=4.0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-volume
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: multitool
spec:
  containers:
  - name: network-multitool
    image: wbitt/network-multitool
    volumeMounts:
    - mountPath: /srv/nfs
      name: vol

  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: nfs-volume

