apiVersion: v1
kind: Pod
metadata:
  name: network-multitool
  labels:
    tier: node
    app: network-multitool
spec:
  containers:
  - name: network-multitool
    image: wbitt/network-multitool
    ports:
    - containerPort: 1280
      name: http-port
    - containerPort: 12443
      name: https-port

