apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ['sh', '-c', 'while true; do echo Salut! >> /output/success.txt; sleep 5; done']
    volumeMounts:
    - mountPath: /output
      name: vol

  - name: network-multitool
    image: wbitt/network-multitool
    volumeMounts:
    - mountPath: /input
      name: vol

  volumes:
  - name: vol
    hostPath:
      path: /var/data

